# Übung 8 Lineare Algebra

## Gaussian Elimination: Rewriting to use pivoting

In this exercise, you'll be rewriting a provided Gaussian elimination routine. Currently, the routine does __NOT__ use pivoting; you will rewrite it to include pivoting.

First, read through and add some code comments to the Gaussian routine __WITHOUT__ pivoting:

In [6]:
import numpy as np
import scipy

In [84]:
def forward_elimination(A, b, n):
    """
    Calculates the forward part of Gaussian elimination.
    """
    # Create the Augmented matrix
    Aug = np.zeros((n,n+1), dtype='float')
    Aug[:,:-1] = A
    Aug[:,-1] = b
    
    for i in np.arange(n-1): # For each row
        for k in np.arange(i+1, n): # Go through all the rows below
            Aug[k,:] = Aug[k,:] - Aug[i,:] * Aug[k,i] / Aug[i,i]
        print('[A|b] = \n', Aug)
    
    A = Aug[:,:-1]
    b = Aug[:,-1]
    
    return A, b

    """
    <<< Variant 1 >>>
    for row in range(0, n-1):
        for i in range(row+1, n):
            factor = A[i,row] / A[row,row]
            for j in range(row, n):
                A[i,j] = A[i,j] - factor * A[row,j]
            b[i] = b[i] - factor * b[row]
        print('A = \n%s and b = %s' % (A,b))
    return A, b
    
    <<< Variant 2 >>>
    for i in np.arange(n-1): # For each rows
        for k in np.arange(i+1, n): # Go through all the rows below
            fac = A[k,i] / A[i,i] # A numerical factor muss be introduced or the vetor b won't be correct!
            A[k,:] = A[k,:] - A[i,:] * fac
            b[k] = b[k] - b[i] * fac
        print('A =\n', A, 'and b =', b)
    return A, b
    """

In [120]:
def back_substitution(A, b, n):
    """"
    Does back substitution, returns the Gauss result.
    """
    # Create the Augmented matrix
    Aug = np.zeros((n,n+1), dtype='float')
    Aug[:,:-1] = A
    Aug[:,-1] = b
    
    Aug[-1,:] = Aug[-1,:] / Aug[-1,-2]
    
    for i in np.arange(n-1, -1, -1): # For each row
        for k in np.arange(i-1, -1, -1): # Go through all the rows above
            Aug[k,:] = Aug[k,:] - Aug[i,:] * Aug[k,k+1]
            Aug[k,:] = Aug[k,:] / Aug[k,k]
        print('[A|b] = \n', Aug)
    
    return Aug[:,-1]

    """
    <<< Variant 1 >>>
    x = np.zeros((n,1))
    x[n-1] = b[n-1] / a[n-1, n-1]
    for row in range(n-2, -1, -1):
        sums = b[row]
        for j in range(row+1, n):
            sums = sums - a[row,j] * x[j]
        x[row] = sums / a[row,row]
    return x
    
    <<< Variant 2 >>
    A[-1,:] = A[-1,:] / A[-1,-1]
    b[n-1] = b[n-1] / A[-1,-1]
    print('A =\n', A, 'and b =', b)
    for i in np.arange(n-1, -1, -1): # For all the rows from the bottom to top
        for k in np.arange(i-1, -1, -1): # Go through all the rows above the current one
            A[k,:] = A[k,:] - A[i,:] * A[k,k+1]
            A[k,:] = A[k,:] / A[k,k]
            b[k] = b[k] - b[i] * A[k,k+1]
            b[k] = b[k] / A[k,k]
        print('A =\n', A, 'and b =', b)
    return b
    """

In [121]:
def gauss(A, b):
    """
    This function performs Gauss elimination without pivoting.
    """
    n = A.shape[0]

    # Check for zero diagonal elements
    if any(np.diag(A)==0):
        raise ZeroDivisionError(('Division by zero will occur; '
                                  'pivoting currently not supported'))

    A, b = forward_elimination(A, b, n)
    return back_substitution(A, b, n)


In [122]:
# Here is a test:
A = np.array([[1, 1, 1, 1],
              [1, -2, -2, -2],
              [1, 4, -4, 1],
              [1, -5, -5, -3]])
b = np.array([0, 4, 2, -4])
x = gauss(A, b)
print('Gauss result is x = \n %s' % x)

[A|b] = 
 [[ 1.  1.  1.  1.  0.]
 [ 0. -3. -3. -3.  4.]
 [ 0.  3. -5.  0.  2.]
 [ 0. -6. -6. -4. -4.]]
[A|b] = 
 [[  1.   1.   1.   1.   0.]
 [  0.  -3.  -3.  -3.   4.]
 [  0.   0.  -8.  -3.   6.]
 [  0.   0.   0.   2. -12.]]
[A|b] = 
 [[  1.   1.   1.   1.   0.]
 [  0.  -3.  -3.  -3.   4.]
 [  0.   0.  -8.  -3.   6.]
 [  0.   0.   0.   2. -12.]]
[A|b] = 
 [[ 1.          1.          1.          0.          6.        ]
 [-0.          1.          1.         -0.          4.66666667]
 [-0.         -0.          1.         -0.          1.5       ]
 [ 0.          0.          0.          1.         -6.        ]]
[A|b] = 
 [[ 1.          1.          0.          0.          4.5       ]
 [ 0.          1.          0.          0.          3.16666667]
 [-0.         -0.          1.         -0.          1.5       ]
 [ 0.          0.          0.          1.         -6.        ]]
[A|b] = 
 [[ 1.          0.          0.          0.          1.33333333]
 [ 0.          1.          0.          0.          3

## Rewriting the routine with pivoting
Now, rewrite the three functions to use pivoting, and name them as:

`forward_elimination_piv()`

`back_substitution_piv()`

`gauss_piv()`

Test against the same case as above.

### 1. The function `forward_elimination_piv(A,b,n)`
In a pratical program we don't really swap the rows inside a matrix for it lowers the performance but tracting only the permutations.

In [9]:
def forward_elimination_piv(A, b, n):
    """
    Calculates the forward part of Gaussian elimination with Pivoting
    """
    for row in range(0, n-1):
        
        for i in range(row+1, n):
            
            factor = A[i,row] / A[row,row]
            
            for j in range(row, n):
                A[i,j] = A[i,j] - factor * A[row,j]
            b[i] = b[i] - factor * b[row]

        print('A = \n%s and b = %s' % (A,b))
    return A, b

In [1]:
def swap_row(A,i,j):
    
    Temp = A[j,:]
    A[j,:] = A[i,:]
    A[i,:] = Temp
    
    return A

back_substitution_piv

In [5]:
def back_substitution_piv(A, b, n):
    """
        Back substitution of A and b with pivoting.
    """
    
    # From the N-TH row (Index: n-1) to the SECOND row (Index: 1)
    for row in range(n-1, 0, -1):
        
        for i in range(row-1, -1, -1):
            factor = A[i,row] / A[row,row]
            
            for j in range(0, n):
                A[i,j] = A[i,j] - factor * A[row,j]
            b[i] = b[i] - factor * b[row]

        print('A = \n%s and b = %s' % (A,b))
        
    return A, b

### The function `gauss_piv(A,b)`

In [10]:
def gauss_piv(A, b):
    """
        Gauss-Jordan Elimination with pivoting.
    """
    # The dimension of the input square matrix A
    n = A.shape[0]

    # Check for zero diagonal elements
    #if any(np.diag(A)==0):
     #   raise ZeroDivisionError(('Division by zero will occur; '
                       #           'pivoting currently not supported'))

    A, b = forward_elimination_piv(A, b, n)
    return back_substitution_piv(A, b, n)

In [11]:
# Test case
A = np.array([[1,  1,  1,  1],
              [1, -2, -2, -2],
              [2,  4, -4,  1],
              [1, -5, -5, -3]],dtype='f')
b = np.array([0, 4, 2, -4])
x = gauss_piv(A, b)

A = 
[[ 1.  1.  1.  1.]
 [ 0. -3. -3. -3.]
 [ 0.  2. -6. -1.]
 [ 0. -6. -6. -4.]] and b = [ 0  4  2 -4]
A = 
[[ 1.  1.  1.  1.]
 [ 0. -3. -3. -3.]
 [ 0.  0. -8. -3.]
 [ 0.  0.  0.  2.]] and b = [  0   4   4 -12]
A = 
[[ 1.  1.  1.  1.]
 [ 0. -3. -3. -3.]
 [ 0.  0. -8. -3.]
 [ 0.  0.  0.  2.]] and b = [  0   4   4 -12]
A = 
[[ 1.  1.  1.  0.]
 [ 0. -3. -3.  0.]
 [ 0.  0. -8.  0.]
 [ 0.  0.  0.  2.]] and b = [  6 -14 -14 -12]
A = 
[[ 1.  1.  0.  0.]
 [ 0. -3.  0.  0.]
 [ 0.  0. -8.  0.]
 [ 0.  0.  0.  2.]] and b = [  4  -8 -14 -12]
A = 
[[ 1.  0.  0.  0.]
 [ 0. -3.  0.  0.]
 [ 0.  0. -8.  0.]
 [ 0.  0.  0.  2.]] and b = [  1  -8 -14 -12]


In [ ]:
# Bonus: Examine the linear algebra Jupyter notebook on Moodle, and start on the homework.